# Generated by Django 2.1 on 2018-08-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mascota', '0002_auto_20180808_1242'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mascota',
            old_name='Persona',
            new_name='persona',
        ),
    ]
